#Solver Args
#RL Args
RL:
  ENV: ActiveLearningEnv-v0
  EPS_START: 0.4
  EPS_STEPS: 75000
  EPS_STOP: 0.05
  GAMMA: 0.99
  GAMMA_N: 0.9320653479069899
  LEARNING_RATE: 0.005
  LOSS_ENTROPY: 0.01
  LOSS_V: 0.5
  MIN_BATCH: 5
  NUM_CLASSES: 10
  N_STEP_RETURN: 7
  OPTIMIZERS: 1
  RUN_TIME: 172800
  STATE_SIZE: 128
  THREADS: 5
  THREAD_DELAY: 0.001
#Classifier Args
classifiers:
  DATASET: MNIST
SHARED:
  NUM_DATA: 100
